# coding: utf-8

from __future__ import absolute_import
from typing import List
from swagger_server.models.base_model_ import Model
from swagger_server.models.book import Book
from swagger_server import util


class ListBooksResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, books: List[Book] = None):  # noqa: E501
        """ListBooksResponse - a model defined in Swagger

        :param books: A list of books in the response.
        :type books: List[Book]
        """
        self.swagger_types = {
            'books': List[Book]
        }

        self.attribute_map = {
            'books': 'books'
        }

        self._books = books

    @classmethod
    def from_dict(cls, dikt) -> 'ListBooksResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListBooksResponse of this ListBooksResponse.
        :rtype: ListBooksResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def books(self) -> List[Book]:
        """Gets the books of this ListBooksResponse.

        :return: The books of this ListBooksResponse.
        :rtype: List[Book]
        """
        return self._books

    @books.setter
    def books(self, books: List[Book]):
        """Sets the books of this ListBooksResponse.

        :param books: The books of this ListBooksResponse.
        :type books: List[Book]
        """
        self._books = books
